trkbranches = [
    "meta.subrun",
    "meta.run",
    "meta.evt",
    "meta.iproc",
    "meta.time",
    "t0PFP",
    "id",
    "clear_cosmic_muon",
    "start.x",
    "start.y",
    "start.z",
    "end.x",
    "end.y",
    "end.z",
    "dir.x",
    "dir.y",
    "dir.z",
    "hit_min_time_p2_tpcE",
    "hit_max_time_p2_tpcE",
    "hit_min_time_p2_tpcW",
    "hit_max_time_p2_tpcW",
    "length",
    "selected",
    "cryostat",

    # Truth Info
    "truth.p.end.x",
    "truth.p.end.y",
    "truth.p.end.z",
    "truth.p.wallin",
]
